export type City = "دبي" | "أبوظبي" | "الشارقة" | "عجمان";
export type SpaceType = "كراج خاص" | "غرفة تخزين" | "موقف سيارة" | "مستودع صغير" | "ساحة خارجية" | "مخزن مكيف" | "موقف RV" | "موقف قارب";
export type Listing = { id:string; title:string; city:City; area:string; price:number; sqm:number; type:SpaceType; rating:number; reviews:number; badge:string; verified:boolean; indoor:boolean; cooled:boolean; vehicle:boolean; dimensions:string; access:string; security:string[]; features:string[]; hostId:string; hostName:string; hostBio:string; occupancyRate:number; images:string[]; description:string };
export const cities: City[] = ["دبي","أبوظبي","الشارقة","عجمان"];
export const spaceTypes: SpaceType[] = ["كراج خاص","غرفة تخزين","موقف سيارة","مستودع صغير","ساحة خارجية","مخزن مكيف","موقف RV","موقف قارب"];
export const prohibitedItems = ["المواد القابلة للاشتعال","المواد غير القانونية","الأطعمة القابلة للتلف","الحيوانات","الأسلحة","الأموال أو المجوهرات عالية القيمة","السكن أو العمل داخل المساحة ممنوع"];
export const users = [
{id:"u1",name:"سارة المنصوري",role:"مستأجر",city:"دبي"},{id:"u2",name:"محمد الكتبي",role:"مستأجر",city:"أبوظبي"},{id:"u3",name:"ليلى الهاشمي",role:"مستأجر",city:"الشارقة"},{id:"u4",name:"خالد النعيمي",role:"مضيف",city:"عجمان"},{id:"u5",name:"ناصر البلوشي",role:"مضيف",city:"دبي"}
];
export const hosts = [
{id:"h1",name:"خالد النعيمي",verified:true,rating:4.9},{id:"h2",name:"مريم الشامسي",verified:true,rating:4.8},{id:"h3",name:"ناصر البلوشي",verified:true,rating:4.7},{id:"h4",name:"عبدالله المرزوقي",verified:false,rating:4.6}
];
const baseSecurity=["كاميرات مراقبة","بوابة مغلقة","هوية المضيف موثقة"];
export const listings: Listing[] = [
{id:"l1",title:"كراج خاص في دبي مارينا",city:"دبي",area:"دبي مارينا",price:640,sqm:18,type:"كراج خاص",rating:4.9,reviews:42,badge:"موثّق",verified:true,indoor:true,cooled:false,vehicle:true,dimensions:"3م × 6م",access:"وصول أسبوعي بتنسيق مسبق",security:baseSecurity,features:["داخلي","مناسب للسيارات","مناسب للأثاث"],hostId:"h1",hostName:"خالد النعيمي",hostBio:"مضيف موثّق لديه كراج خاص نظيف وآمن داخل مبنى سكني.",occupancyRate:.82,images:["from-blue-600 to-emerald-400","from-slate-700 to-blue-500","from-cyan-500 to-slate-800"],description:"مساحة نظيفة ومغلقة مناسبة للأثاث أو سيارة واحدة، الموقع تقريبي ولا يظهر العنوان الكامل إلا بعد قبول الطلب."},
{id:"l2",title:"غرفة تخزين مكيفة في الخليج التجاري",city:"دبي",area:"الخليج التجاري",price:520,sqm:12,type:"مخزن مكيف",rating:4.8,reviews:36,badge:"مكيف",verified:true,indoor:true,cooled:true,vehicle:false,dimensions:"3م × 4م",access:"وصول 24/7",security:[...baseSecurity,"حارس مبنى"],features:["مكيف","داخلي","وصول 24/7"],hostId:"h2",hostName:"مريم الشامسي",hostBio:"مساحات داخلية منظمة ومناسبة للصناديق والأثاث الخفيف.",occupancyRate:.76,images:["from-emerald-500 to-blue-500","from-sky-500 to-indigo-500"],description:"غرفة مكيفة داخل مبنى حديث، مناسبة للصناديق والوثائق والأثاث الحساس للحرارة."},
{id:"l3",title:"موقف سيارة مظلل في جميرا",city:"دبي",area:"جميرا",price:390,sqm:14,type:"موقف سيارة",rating:4.6,reviews:20,badge:"خصم 10%",verified:true,indoor:false,cooled:false,vehicle:true,dimensions:"2.5م × 5.5م",access:"وصول يومي",security:["بوابة مغلقة","منطقة سكنية آمنة"],features:["خارجي","مناسب للسيارات"],hostId:"h3",hostName:"ناصر البلوشي",hostBio:"مضيف متجاوب يوفر موقفًا مظللًا قريبًا من الطرق الرئيسية.",occupancyRate:.68,images:["from-slate-600 to-teal-400"],description:"موقف مظلل في منطقة هادئة، مناسب للسيارات الخاصة لفترات شهرية."},
{id:"l4",title:"مستودع صغير في مصفح",city:"أبوظبي",area:"مصفح",price:880,sqm:28,type:"مستودع صغير",rating:4.7,reviews:31,badge:"الأكثر طلبًا",verified:true,indoor:true,cooled:false,vehicle:false,dimensions:"4م × 7م",access:"الأحد إلى الجمعة",security:[...baseSecurity,"سجل دخول"],features:["داخلي","مناسب للمعدات","بوابة مغلقة"],hostId:"h4",hostName:"عبدالله المرزوقي",hostBio:"مستودع عملي للشركات الصغيرة والمعدات غير الخطرة.",occupancyRate:.91,images:["from-indigo-600 to-emerald-500"],description:"مساحة أكبر للشركات الصغيرة والمعدات، مع سياسة مواد ممنوعة واضحة داخل التطبيق."},
{id:"l5",title:"ساحة خارجية للقوارب في البطين",city:"أبوظبي",area:"البطين",price:730,sqm:32,type:"موقف قارب",rating:4.5,reviews:14,badge:"جديد",verified:false,indoor:false,cooled:false,vehicle:true,dimensions:"4م × 8م",access:"وصول أسبوعي",security:["سور محيط","بوابة مغلقة"],features:["خارجي","مناسب للقوارب"],hostId:"h1",hostName:"خالد النعيمي",hostBio:"يدير عدة مساحات للمركبات والقوارب.",occupancyRate:.57,images:["from-cyan-600 to-blue-900"],description:"ساحة خارجية واسعة للمركبات البحرية الصغيرة، الموقع المعروض تقريبي."},
{id:"l6",title:"غرفة تخزين داخل في المجاز",city:"الشارقة",area:"المجاز",price:310,sqm:9,type:"غرفة تخزين",rating:4.4,reviews:18,badge:"موثّق",verified:true,indoor:true,cooled:false,vehicle:false,dimensions:"3م × 3م",access:"مرتان أسبوعيًا",security:[...baseSecurity],features:["داخلي","مناسب للصناديق"],hostId:"h2",hostName:"مريم الشامسي",hostBio:"تركز على مساحات التخزين المنزلية النظيفة.",occupancyRate:.73,images:["from-teal-500 to-slate-700"],description:"حل اقتصادي للتخزين الشهري للصناديق والأغراض المنزلية."},
{id:"l7",title:"مخزن مكيف في النهدة",city:"الشارقة",area:"النهدة",price:450,sqm:11,type:"مخزن مكيف",rating:4.8,reviews:27,badge:"مكيف",verified:true,indoor:true,cooled:true,vehicle:false,dimensions:"2.8م × 4م",access:"وصول 24/7",security:[...baseSecurity,"إنذار دخول"],features:["مكيف","داخلي","مناسب للأثاث"],hostId:"h3",hostName:"ناصر البلوشي",hostBio:"مساحة مكيفة مخصصة للتخزين الآمن.",occupancyRate:.84,images:["from-blue-500 to-green-400"],description:"مناسب للأثاث والملابس والوثائق مع تحكم جيد بالحرارة."},
{id:"l8",title:"كراج في الراشدية",city:"عجمان",area:"الراشدية",price:280,sqm:16,type:"كراج خاص",rating:4.3,reviews:12,badge:"الأقل سعرًا",verified:false,indoor:true,cooled:false,vehicle:true,dimensions:"3.2م × 5م",access:"بتنسيق مسبق",security:["قفل خاص","منطقة سكنية"],features:["داخلي","مناسب للسيارات"],hostId:"h4",hostName:"عبدالله المرزوقي",hostBio:"مساحة بسيطة بسعر مناسب للتخزين الشهري.",occupancyRate:.62,images:["from-slate-500 to-emerald-500"],description:"كراج خاص اقتصادي في عجمان مناسب لسيارة أو تخزين منزلي."},
{id:"l9",title:"موقف RV في الياسمين",city:"عجمان",area:"الياسمين",price:690,sqm:35,type:"موقف RV",rating:4.6,reviews:16,badge:"وصول 24/7",verified:true,indoor:false,cooled:false,vehicle:true,dimensions:"4م × 8.8م",access:"وصول 24/7",security:["بوابة مغلقة","إضاءة ليلية"],features:["خارجي","مناسب للمركبات","وصول 24/7"],hostId:"h1",hostName:"خالد النعيمي",hostBio:"خبرة في استضافة المركبات الكبيرة.",occupancyRate:.79,images:["from-green-500 to-blue-700"],description:"موقف واسع للمركبات الكبيرة وRV مع وصول مرن."},
{id:"l10",title:"مستودع مصغر في القوز",city:"دبي",area:"القوز",price:760,sqm:22,type:"مستودع صغير",rating:4.7,reviews:24,badge:"موثّق",verified:true,indoor:true,cooled:false,vehicle:false,dimensions:"4م × 5.5م",access:"أيام العمل",security:[...baseSecurity,"نظام دخول"],features:["داخلي","مناسب للمعدات"],hostId:"h2",hostName:"مريم الشامسي",hostBio:"تدير مساحة مستودعية مناسبة للأعمال الصغيرة.",occupancyRate:.88,images:["from-blue-800 to-emerald-500"],description:"مخزن عملي قريب من مناطق الأعمال، بدون دفع حقيقي في هذا النموذج."},
{id:"l11",title:"موقف قارب في الخان",city:"الشارقة",area:"الخان",price:610,sqm:26,type:"موقف قارب",rating:4.2,reviews:9,badge:"جديد",verified:false,indoor:false,cooled:false,vehicle:true,dimensions:"3.5م × 7.5م",access:"وصول أسبوعي",security:["سور محيط","إضاءة"],features:["خارجي","مناسب للقوارب"],hostId:"h3",hostName:"ناصر البلوشي",hostBio:"موقع خارجي قريب من الطرق الساحلية.",occupancyRate:.52,images:["from-cyan-700 to-slate-600"],description:"موقف خارجي للقوارب الصغيرة والمقطورات."},
{id:"l12",title:"غرفة داخلية في المشرف",city:"أبوظبي",area:"المشرف",price:430,sqm:10,type:"غرفة تخزين",rating:4.9,reviews:33,badge:"الأعلى تقييمًا",verified:true,indoor:true,cooled:true,vehicle:false,dimensions:"2.5م × 4م",access:"ثلاث مرات أسبوعيًا",security:[...baseSecurity,"مكيف"],features:["مكيف","داخلي","مناسب للأثاث"],hostId:"h4",hostName:"عبدالله المرزوقي",hostBio:"مضيف موثّق يلتزم بسياسات الوصول والمواد الممنوعة.",occupancyRate:.86,images:["from-emerald-600 to-indigo-600"],description:"غرفة تخزين داخلية ممتازة للأثاث والصناديق في أبوظبي."}
];
export const bookings = [
{id:"b1",listingId:"l1",space:"كراج خاص في دبي مارينا",date:"2026-07-10",price:640,status:"نشط"},{id:"b2",listingId:"l4",space:"مستودع صغير في مصفح",date:"2026-07-15",price:880,status:"بانتظار الموافقة"},{id:"b3",listingId:"l7",space:"مخزن مكيف في النهدة",date:"2026-06-01",price:450,status:"نشط"},{id:"b4",listingId:"l8",space:"كراج في الراشدية",date:"2026-05-20",price:280,status:"سابق"},{id:"b5",listingId:"l10",space:"مستودع مصغر في القوز",date:"2026-08-01",price:760,status:"بانتظار الموافقة"},{id:"b6",listingId:"l12",space:"غرفة داخلية في المشرف",date:"2026-04-01",price:430,status:"سابق"},{id:"b7",listingId:"l2",space:"غرفة تخزين مكيفة",date:"2026-07-05",price:520,status:"نشط"},{id:"b8",listingId:"l9",space:"موقف RV في الياسمين",date:"2026-07-22",price:690,status:"بانتظار الموافقة"}
];
export const reviews = Array.from({length:10},(_,i)=>({id:`r${i+1}`,user:users[i%users.length].name,rating:[5,5,4,5,4][i%5],text:["تجربة سهلة والمساحة كما في الوصف.","المضيف متجاوب والموقع مناسب.","سعر جيد مقارنة بالتخزين التقليدي.","أعجبني وضوح سياسة الوصول.","الحجز التجريبي سلس وواضح."][i%5]}));
export const conversations = [
{id:"m1",listingId:"l1",name:"خالد النعيمي",last:"المساحة متاحة بداية الشهر القادم.",messages:["مرحبًا، هل الكراج مناسب لسيارة سيدان؟","نعم مناسب، والوصول أسبوعي بتنسيق مسبق."]},{id:"m2",listingId:"l2",name:"مريم الشامسي",last:"المخزن مكيف طوال اليوم.",messages:["هل يمكن تخزين وثائق؟","نعم بشرط ألا تكون عالية القيمة."]},{id:"m3",listingId:"l4",name:"عبدالله المرزوقي",last:"أرسل نوع المعدات للتأكد.",messages:["أريد تخزين معدات تصوير.","مسموح إن لم تحتوي بطاريات خطرة."]},{id:"m4",listingId:"l7",name:"ناصر البلوشي",last:"يمكنك الحجز لمدة 3 أشهر.",messages:["هل يوجد خصم لمدة أطول؟","يمكننا مراجعة السعر لستة أشهر."]},{id:"m5",listingId:"l9",name:"خالد النعيمي",last:"الموقف مناسب للمركبات الكبيرة.",messages:["هل يناسب RV بطول 7 أمتار؟","نعم المساحة 8.8 متر تقريبًا."]},{id:"m6",listingId:"l12",name:"عبدالله المرزوقي",last:"العنوان الكامل يظهر بعد قبول الطلب.",messages:["أين الموقع تحديدًا؟","الموقع تقريبي في المشرف لحين قبول الحجز."]}
];
export const adminStats = { users: 5, spaces: listings.length, bookings: bookings.length, gmv: bookings.reduce((s,b)=>s+b.price,0) };
export function getListing(id:string){ return listings.find(l=>l.id===id) || listings[0]; }
